javascripts:
  workspace:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/json2.js
    - public/javascripts/underscore-min.js
    - public/javascripts/handlebars-1.0.0.beta.2.js
    - public/javascripts/backbone-min.js
    - public/javascripts/backbone/helpers/*
    - public/javascripts/backbone/models/*
    - public/javascripts/backbone/views/*
    - public/javascripts/application.js
  tools:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery_ujs.js
