development:
  enable_star: 1
  min_infix_len: 3
test:
  enable_star: 1
  min_infix_len: 3
production:
  enable_star: 1
  min_infix_len: 3
  pid_file: /var/run/sphinxsearch/searchd.pid
  searchd_file_path: /var/db/sphinxsearch/data
  searchd_log_file: /var/log/searchd.log
  query_log_file: /var/log/searchd_query.log
